language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install -n --dev --prefer-source

script:
  ## LINT
  - find thinkphp ! -path "thinkphp/vendor/*" -type f -name \*.php -exec php -l {} \;
  ## PHP_CodeSniffer
  - thinkphp/vendor/bin/phpcs --standard=PSR2 --warning-severity=6 --ignore="thinkphp/vendor/*" thinkphp
  ## PHP Copy/Paste Detector
  - thinkphp/vendor/bin/phpcpd --verbose --exclude vendor thinkphp
  ## PHPLOC
  - thinkphp/vendor/bin/phploc --exclude vendor thinkphp
  ## PHPUNIT
  - thinkphp/vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

